race$NAME <- stringr::str_replace(race$NAME, '-AL-AL', '-AL')
race$NAME <- stringr::str_replace(race$NAME, '-AR-AR', '-AR')
race$NAME <- stringr::str_replace(race$NAME, '-AZ-AZ', '-AZ')
race$NAME <- stringr::str_replace(race$NAME, '-CA-CA', '-CA')
race$NAME <- stringr::str_replace(race$NAME, '-CO-CO', '-CO')
race$NAME <- stringr::str_replace(race$NAME, '-CT-CT', '-CT')
race$NAME <- stringr::str_replace(race$NAME, '-DE-DE', '-DE')
race$NAME <- stringr::str_replace(race$NAME, '-DC-DC', '-DC')
race$NAME <- stringr::str_replace(race$NAME, '-FL-FL', '-FL')
race$NAME <- stringr::str_replace(race$NAME, '-GA-GA', '-GA')
race$NAME <- stringr::str_replace(race$NAME, '-IA-IA', '-IA')
race$NAME <- stringr::str_replace(race$NAME, '-ID-ID', '-ID')
race$NAME <- stringr::str_replace(race$NAME, '-IL-IL', '-IL')
race$NAME <- stringr::str_replace(race$NAME, '-IN-IN', '-IN')
race$NAME <- stringr::str_replace(race$NAME, '-KS-KS', '-KS')
race$NAME <- stringr::str_replace(race$NAME, '-KY-KY', '-KY')
race$NAME <- stringr::str_replace(race$NAME, '-LA-LA', '-LA')
race$NAME <- stringr::str_replace(race$NAME, '-MD-MD', '-MD')
race$NAME <- stringr::str_replace(race$NAME, '-ME-ME', '-ME')
race$NAME <- stringr::str_replace(race$NAME, '-MN-MN', '-MN')
race$NAME <- stringr::str_replace(race$NAME, '-MA-MA', '-MA')
race$NAME <- stringr::str_replace(race$NAME, '-MI-MI', '-MI')
race$NAME <- stringr::str_replace(race$NAME, '-MS-MS', '-MS')
race$NAME <- stringr::str_replace(race$NAME, '-MO-MO', '-MO')
race$NAME <- stringr::str_replace(race$NAME, '-MT-MT', '-MT')
race$NAME <- stringr::str_replace(race$NAME, '-NE-NE', '-NE')
race$NAME <- stringr::str_replace(race$NAME, '-NV-NV', '-NV')
race$NAME <- stringr::str_replace(race$NAME, '-ND-ND', '-ND')
race$NAME <- stringr::str_replace(race$NAME, '-NC-NC', '-NC')
race$NAME <- stringr::str_replace(race$NAME, '-NJ-NJ', '-NJ')
race$NAME <- stringr::str_replace(race$NAME, '-NY-NY', '-NY')
race$NAME <- stringr::str_replace(race$NAME, '-NH-NH', '-NH')
race$NAME <- stringr::str_replace(race$NAME, '-NM-NM', '-NM')
race$NAME <- stringr::str_replace(race$NAME, '-OH-OH', '-OH')
race$NAME <- stringr::str_replace(race$NAME, '-OK-OK', '-OK')
race$NAME <- stringr::str_replace(race$NAME, '-OR-OR', '-OR')
race$NAME <- stringr::str_replace(race$NAME, '-PA-PA', '-PA')
race$NAME <- stringr::str_replace(race$NAME, '-RH-RI', '-RI')
race$NAME <- stringr::str_replace(race$NAME, '-SD-SD', '-SD')
race$NAME <- stringr::str_replace(race$NAME, '-SC-SC', '-SC')
race$NAME <- stringr::str_replace(race$NAME, '-TN-TN', '-TN')
race$NAME <- stringr::str_replace(race$NAME, '-TX-TX', '-TX')
race$NAME <- stringr::str_replace(race$NAME, '-UT-UT', '-UT')
race$NAME <- stringr::str_replace(race$NAME, '-VA-VA', '-VA')
race$NAME <- stringr::str_replace(race$NAME, '-VT-VT', '-VT')
race$NAME <- stringr::str_replace(race$NAME, '-WA-WA', '-WA')
race$NAME <- stringr::str_replace(race$NAME, '-WV-WV', '-WV')
race$NAME <- stringr::str_replace(race$NAME, '-WI-WI', '-WI')
race$NAME <- stringr::str_replace(race$NAME, '-WY-WY', '-WY')
race$NAME <- stringr::str_replace(race$NAME, '-LA-LA', '-LA')

race$STATE_NAME <- gsub("RH", "RI", race$STATE_NAME)
race[["NAME"]] <- 
  with(race, ifelse(STATE_NAME == 'RI', paste0(NAME, "-", STATE_NAME), NAME))



race[["NAME"]] <- 
  with(race, ifelse(STATE_NAME == 'MA', paste0(NAME, "-", STATE_NAME), NAME))

write.csv(race, "C:/Users/Clown Baby/Desktop/Countyapp/Countyapp/test_covid/race.csv", row.names = FALSE)